AllCops:

  DisabledByDefault: true

  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx

Metrics/LineLength:
    Description: 'Limit lines to 220 characters.'
    StyleGuide: 'None'
    Enabled: true
    AutoCorrect: false
    Max: 220
    AllowHeredoc: true
    AllowURI: true
    URISchemes:
      - http
      - https
    IgnoreCopDirectives: false
    IgnoredPatterns: []